### ISSUE TITLE
Issue Landmine

### ISSUE THREAD

**Issue by DHStyle541** [OnionMilk-Mods/crawlingmine#1]
Very good mod, but many bugs like
1. Landmine's sound suddenly disappears
2. Cannot be scanned
3. Spam Error Logs

![image](https://github.com/OnionMilk-Mods/crawlingmine/assets/154591650/96565ed9-8e77-4702-9f75-4c9b0547c960)
^ this happens when blowing up a Landmine

**Comment by zbigniewcebula** [comment]
Hello! Thank you for reporting that, I'll fix it in few days :)

- "Cannot be scanned" means that when you hit "scan" it does not show anything? 
- "Sound" is about every sound or only one of them? (as far as I recall idle and explosion)
- This error msg is weird, I do not affect EnemyAI at all. Landmine script is not related to it either, are you sure it's caused by my scripts? (do you have any other mods installed that affect Centipede?)

**Comment by DHStyle541** [comment]
1. Cannot be scanned like, when Landmine move can't scan
2. When landmine move no sfx like beep beep, only Light Red showing
3. Idk but when Landmine destroy get spam console like that. maybe conflict Lethal Escape?

sry my eng so badd

**Comment by zbigniewcebula** [comment]
I hope [this](https://github.com/OnionMilk-Mods/crawlingmine/releases/tag/1.0.2) release will be helpful :D
(I've also updated the thunderstore entry)

- Scanning should work
- Beep should be present
- I fixed bug in console but it's not from my mod, but it does not affect anything pretty much so, free fix in the case of other mod failing in this specific place ¯\\_(ツ)_/¯

Don't worry about English, I'm not native too.
